#spring.datasource.url=jdbc:mysql://localhost/demo
#spring.datasource.username=root
#spring.datasource.password=
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver

server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demopropia
    username: root
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect